name: zakazflow
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Ui
  extended_masked_text: ^2.3.1
  pinput: ^2.2.31
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.1.3
  dots_indicator: ^2.0.0
  flutter_switch: ^0.3.2
  pull_to_refresh_flutter3: ^2.0.1
  pie_chart: ^5.3.2
  loader_overlay: ^2.3.2
  bottom_sheet_bar: ^2.3.9
  flutter_custom_clippers: ^2.1.0

  #Animation
  countup: ^0.1.4
  expandable: ^5.0.1

  #notifications
  flutter_local_notifications: ^15.1.2
  firebase_core: ^2.17.0
  firebase_messaging: ^14.7.0

  #support web view
  url_launcher: ^6.1.14

  #router
  auto_route: ^7.8.3

  #asset management
  flutter_svg: ^2.0.7
  spider: ^4.2.1

  # Internet connectivity
  connectivity_plus: ^4.0.2

  #state management
  bloc: ^8.1.2
  meta: ^1.8.0
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  bloc_concurrency: ^0.2.2
  flutter_redux: ^0.10.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0

  #network
  json_annotation: ^4.3.0
  dio: ^5.3.3
  http_mock_adapter: ^0.6.0

  # Dependency injection
  injectable: ^2.1.2
  get_it: ^7.2.0

  # Local Storage
  quiver: ^3.2.1
  shared_preferences: ^2.1.2
  flutter_secure_storage: ^8.0.0

  # Features
  share_plus: ^6.0.2
  collection: ^1.15.0

  #Logging
  l: ^4.0.2
  stack_trace: ^1.11.0
  firebase_crashlytics: ^3.3.4

  # Localication
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  json_serializable: ^6.0.1
  auto_route_generator: ^7.3.1
  injectable_generator: ^2.1.2
  lint: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  flutter_animated_icons: ^1.0.1
  flutter_staggered_animations: ^1.1.1

  #Test
  test: ^1.24.1
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  min_sdk_android: 21
  android: "launcher_icon"
  ios: true
  # remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#F84C0A"
  image: assets/images/splash.png
  color_dark: "#F84C0A"
  ios: true
  android: true
  android_12:
    image: assets/images/splash.png
  fullscreen: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100

        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300

        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          style: normal
          weight: 400

        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500

        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
